// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WorkflowService.Infrastructure.Persistence;

#nullable disable

namespace WorkflowService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WorkflowDbContext))]
    [Migration("20260317182437_AddStageDefinitions")]
    partial class AddStageDefinitions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WorkflowService.Domain.Entities.StageDefinitionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<string>("RoleRequired")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("role_required");

                    b.Property<int>("SlaDays")
                        .HasColumnType("integer")
                        .HasColumnName("sla_days");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("stage_name");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_definition_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowDefinitionId");

                    b.ToTable("workflow_definition_stages", (string)null);
                });

            modelBuilder.Entity("WorkflowService.Domain.Entities.WorkflowDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.ToTable("workflow_definitions", (string)null);
                });

            modelBuilder.Entity("WorkflowService.Domain.Entities.WorkflowInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("CurrentStageOrder")
                        .HasColumnType("integer")
                        .HasColumnName("current_stage_order");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("DocumentTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("document_title");

                    b.Property<Guid>("InitiatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("initiated_by_user_id");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_definition_id");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_workflow_instances_document_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_workflow_instances_tenant_id");

                    b.ToTable("workflow_instances", (string)null);
                });

            modelBuilder.Entity("WorkflowService.Domain.Entities.WorkflowStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssignedToEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("assigned_to_email");

                    b.Property<Guid>("AssignedToUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_to_user_id");

                    b.Property<string>("Comments")
                        .HasColumnType("text")
                        .HasColumnName("comments");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<DateTime>("SlaDeadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sla_deadline");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("stage_name");

                    b.Property<int>("StageOrder")
                        .HasColumnType("integer")
                        .HasColumnName("stage_order");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("WorkflowInstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_instance_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowInstanceId");

                    b.ToTable("workflow_stages", (string)null);
                });

            modelBuilder.Entity("WorkflowService.Domain.Entities.StageDefinitionEntity", b =>
                {
                    b.HasOne("WorkflowService.Domain.Entities.WorkflowDefinition", null)
                        .WithMany("Stages")
                        .HasForeignKey("WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WorkflowService.Domain.Entities.WorkflowStage", b =>
                {
                    b.HasOne("WorkflowService.Domain.Entities.WorkflowInstance", null)
                        .WithMany("Stages")
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WorkflowService.Domain.Entities.WorkflowDefinition", b =>
                {
                    b.Navigation("Stages");
                });

            modelBuilder.Entity("WorkflowService.Domain.Entities.WorkflowInstance", b =>
                {
                    b.Navigation("Stages");
                });
#pragma warning restore 612, 618
        }
    }
}
